name = "IonicElectrochemicalCells"
uuid = "9b3a78ad-cd55-49eb-a790-9ac44eee3717"
authors = ["Petr Vágner", "Vojta Miloš", "Jürgen Fuhrmann"]
version = "0.1.0"

[deps]
CompositeStructs = "534720e6-2374-40c5-8712-bf9a2f1643c6"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ModelParameters = "4744a3fa-6c31-4707-899e-a3298e4618ad"
SamplerIO = "bca66995-4ecd-408b-bba5-fd5fcf25f571"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"

[compat]
VoronoiFVM = "0.18"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
